# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/backend" # Location of package manifests
    schedule:
      interval: "weekly"
    reviewers:
    - "OnlyNico43"
    
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/websocket" # Location of package manifests
    schedule:
      interval: "weekly"
    reviewers:
    - "OnlyNico43"
    
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/lib/database" # Location of package manifests
    schedule:
      interval: "weekly"
    reviewers:
    - "OnlyNico43"
    
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/lib/jwt" # Location of package manifests
    schedule:
      interval: "weekly"
    reviewers:
    - "OnlyNico43"
    
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/lib/logger" # Location of package manifests
    schedule:
      interval: "weekly"
    reviewers:
    - "OnlyNico43"
