repos:
  - repo: local
    hooks:
    - id: gofmt
      name: gofmt
      entry: gofmt -w .
      language: system
      pass_filenames: false

    - id: go-mod-tidy
      name: go-mod-tidy
      entry: go mod tidy
      language: system
      pass_filenames: false
      require_serial: true
    
    - id: golangci-lint
      name: golangci-lint
      entry: golangci-lint run
      language: system
      pass_filenames: false
      require_serial: true
      