export enum ErrorCodes {
  UNAUTHORIZED = 'UNAUTHORIZED',
  API_ERROR = 'API_ERROR',
  NOT_ALLOWED = 'NOT_ALLOWED',
  NOT_FOUND = 'NOT_FOUND',
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  WRONG_CREDENTIALS = 'WRONG_CREDENTIALS',
}
