name: Build Project

# Trigger the workflow on push or pull request to "main" branch or tags that match 'v*'
on:
  push:
    branches:
      - main
      - release/*
      - feature/migration-go
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Cache Go modules
        id: cache-go-modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check Cache Hit
        run: |
          if [ "${{ steps.cache-go-modules.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit, skipping some steps..."
          else
            echo "Cache miss, performing additional steps..."
            go mod tidy
            go mod download
          fi      

      - name: Build
        run: |
          # Ensure the binary is statically linked to avoid libc issues with Alpine
          CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o easyflow-backend .

      - name: Build Docker image
        run: |
          docker build -t easyflow-backend-image -f Docker/Dockerfile .
      
      - name: Save Docker image as tar file
        run: |
          docker save easyflow-backend-image:latest -o easyflow-backend-image.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: easyflow-backend-image
          path: easyflow-backend-image.tar
