name: CI/CD

on:
  push:
    branches:
      - "*"
  release:
    types:
      - "published"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: format
        run: gofmt -l -e .

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: build
        run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./bin/easyflow-backend ./src

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./bin/easyflow-backend
          name: easyflow-backend-${{ github.sha }}
          if-no-files-found: error

  docker:
    needs: [build, lint, format]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          path: ./bin/easyflow-backend
          name: easyflow-backend-${{ github.sha }}

      - name: login to docker
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: create image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}
          tags: |
            type=raw,value=dev,enable=${{ github.ref_name == 'main' }}
            type=raw,value=latest,enable=${{ github.event_name == 'release' }}
            type=raw,value=${{ github.ref_name }},enable=${{ github.event_name == 'release' }}

      - name: build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          push: ${{ github.ref_name == 'main' || github.event_name == 'release'  }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' || github.event_name == 'release'

    steps:
      - name: setup railway cli
        run: npm i -g @railway/cli

      - name: trigger redeploy on railway development
        if: github.ref_name == 'main'
        run: RAILWAY_TOKEN=${{ secrets.RAILWAY_DEV_TOKEN }} railway redeploy -s ${{ vars.RAILWAY_SERVICE_NAME }} -y

      - name: trigger redeploy on railway production
        if: github.event_name == 'release'
        run: RAILWAY_TOKEN=${{ secrets.RAILWAY_PROD_TOKEN }} railway redeploy -s ${{ vars.RAILWAY_SERVICE_NAME }} -y
